version: '3.9'

services:
  app:
    build: ./app
    container_name: app
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: pass
    depends_on:
      - db
    networks:
      - mynet

  db:
    healthcheck:
      test:["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      retries: 5
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - mynet

networks:
  mynet:

volumes:
  db_data:

restart: always
