version = 5.5.0
archive_dir = /etc/letsencrypt/archive/xwarhamx.ru
cert = /etc/letsencrypt/live/xwarhamx.ru/cert.pem
privkey = /etc/letsencrypt/live/xwarhamx.ru/privkey.pem
chain = /etc/letsencrypt/live/xwarhamx.ru/chain.pem
fullchain = /etc/letsencrypt/live/xwarhamx.ru/fullchain.pem
[renewalparams]
account = 2c3fc4b20b81195a1142be1e5413339a
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
www.xwarhamx.ru = /var/www/certbot
xwarhamx.ru = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-05-11T17:14:07
